# ─────────────────────────────────────────────────────────────
#  Staging Inventory  (inventory/staging/hosts.ini)
#  Usage: ansible-playbook -i inventory/staging site.yml
# ─────────────────────────────────────────────────────────────

[webservers]
staging-web-01 ansible_host=YOUR_STAGING_EC2_IP  ansible_user=deploy

[app:children]
webservers

[all:vars]
ansible_python_interpreter=/usr/bin/python3
env=staging