# ─────────────────────────────────────────────────────────────
#  Production Inventory  (inventory/prod/hosts.ini)
#  Usage: ansible-playbook -i inventory/prod site.yml
# ─────────────────────────────────────────────────────────────

[webservers]
prod-web-01 ansible_host=MY_PROD_EC2_IP ansible_user=deploy

[app:children]
webservers

[all:vars]
ansible_python_interpreter=/usr/bin/python3
env=prod