##############################################################################
# main.tf — Root Module (Orchestrator)
#
# This file ties all modules together. Think of it as the "main function"
# that calls other functions (modules).
#
# MODULE FLOW:
#   networking → compute + database + storage
#
# The networking module runs first because it creates the VPC and subnets
# that compute and database depend on. Terraform figures out this dependency
# automatically from the references (module.networking.vpc_id, etc.)
##############################################################################

# ============================================================================
# DATA SOURCES
# Look up existing AWS information we don't manage with Terraform
# ============================================================================

# Get the latest Ubuntu 22.04 LTS AMI from Canonical's official account.
# This ensures we always launch instances with the latest patched AMI.
# Instead of hardcoding "ami-0c55b159cbfafe1f0" (which is region-specific
# and becomes outdated), we dynamically look it up.
data "aws_ami" "ubuntu" {
  most_recent = true
  owners      = ["099720109477"] # Canonical's AWS account ID

  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }

  filter {
    name   = "architecture"
    values = ["x86_64"]
  }
}

# Get the current AWS account ID and caller identity.
# Useful for constructing ARNs and for conditional logic.
data "aws_caller_identity" "current" {}

# ============================================================================
# MODULE: NETWORKING
# Creates the entire network layer: VPC, subnets, routing, gateways.
# Everything else sits inside this network.
# ============================================================================
module "networking" {
  source = "./modules/networking"

  # What to name resources
  name_prefix = local.name_prefix
  environment = local.environment

  # Network topology
  vpc_cidr           = var.vpc_cidr
  availability_zones = var.availability_zones

  # NAT Gateway controls whether private subnets can reach the internet.
  # Production: enable it (servers need to pull Docker images, send emails, etc.)
  # Dev: can disable to save $32/month
  enable_nat_gateway = local.config.enable_nat_gateway
  single_nat_gateway = local.config.single_nat_gateway

  tags = local.common_tags
}

# ============================================================================
# MODULE: COMPUTE
# Creates EC2 instances, Auto Scaling Group, Application Load Balancer.
# The actual servers that run your Spring Boot backend.
# ============================================================================
module "compute" {
  source = "./modules/compute"

  name_prefix = local.name_prefix
  environment = local.environment

  # Network placement — from networking module outputs
  vpc_id             = module.networking.vpc_id
  public_subnet_ids  = module.networking.public_subnet_ids  # ALB goes here (internet-facing)
  private_subnet_ids = module.networking.private_subnet_ids # EC2 goes here (not directly exposed)

  # Instance configuration
  ami_id        = data.aws_ami.ubuntu.id
  instance_type = local.effective_instance_type
  key_pair_name = var.key_pair_name

  # Auto Scaling
  min_instances         = local.effective_min_instances
  desired_instances     = local.effective_desired_instances
  max_instances         = local.effective_max_instances
  enable_spot_instances = local.config.enable_spot_instances

  # Application config injected as user_data (startup script)
  backend_image_tag  = var.backend_image_tag
  frontend_image_tag = var.frontend_image_tag

  # Database connection — passed from database module
  db_endpoint = module.database.db_endpoint
  db_name     = var.db_name
  db_username = var.db_username
  db_password = module.database.db_password # Generated by database module

  # S3 access
  s3_bucket_name = module.storage.uploads_bucket_name
  aws_region     = var.aws_region

  tags = local.common_tags
}

# ============================================================================
# MODULE: DATABASE
# Creates RDS PostgreSQL instance with security groups, subnet groups,
# parameter groups, and automated backups.
# ============================================================================
module "database" {
  source = "./modules/database"

  name_prefix = local.name_prefix
  environment = local.environment

  # Network placement — databases go in private (database) subnets
  vpc_id              = module.networking.vpc_id
  database_subnet_ids = module.networking.database_subnet_ids

  # Security group of the EC2 instances (only they can connect to the database)
  app_security_group_id = module.compute.app_security_group_id

  # Database configuration
  db_instance_class        = local.effective_db_instance_class
  db_name                  = var.db_name
  db_username              = var.db_username
  db_allocated_storage     = var.db_allocated_storage
  db_max_allocated_storage = var.db_max_allocated_storage

  # Reliability settings
  db_multi_az              = local.effective_db_multi_az
  db_backup_retention_days = local.effective_db_backup_retention_days
  db_deletion_protection   = local.effective_db_deletion_protection

  tags = local.common_tags
}

# ============================================================================
# MODULE: STORAGE
# Creates S3 buckets for file uploads, reports, and database backups.
# ============================================================================
module "storage" {
  source = "./modules/storage"

  name_prefix           = local.name_prefix
  environment           = local.environment
  s3_bucket_name_prefix = var.s3_bucket_name_prefix

  enable_versioning = var.enable_s3_versioning

  # Grant EC2 instances access to upload/download files
  ec2_instance_role_name = module.compute.ec2_instance_role_name

  tags = local.common_tags
}