package com.moeware.ims.dto.dashboard;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import java.util.Map;

import com.moeware.ims.enums.dashboard.DashboardPeriod;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Dashboard sales analytics response.
 * Includes order summaries, status breakdowns, top products/customers, and
 * daily trends.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "Sales analytics for the requested period, including totals, top-N rankings, " +
        "daily trend data, and period-over-period growth metrics")
public class DashboardSalesAnalyticsResponse {

    @Schema(description = "The resolved time window (matches the period request parameter)", example = "MONTH")
    private DashboardPeriod period;

    @Schema(description = "Inclusive start date of the analytics window", example = "2026-02-01")
    private LocalDate startDate;

    @Schema(description = "Inclusive end date of the analytics window", example = "2026-02-28")
    private LocalDate endDate;

    @Schema(description = "Aggregate totals for the period")
    private SummaryDTO summary;

    @Schema(description = "Order count grouped by status name (e.g. PENDING, CONFIRMED, DELIVERED)")
    private Map<String, Integer> byStatus;

    @Schema(description = "Top 10 products ranked by revenue in the period")
    private List<TopProductDTO> topProducts;

    @Schema(description = "Top 10 customers ranked by total spend in the period")
    private List<TopCustomerDTO> topCustomers;

    @Schema(description = "Day-by-day order count, revenue, and items-sold data points")
    private List<DailyTrendDTO> dailyTrend;

    @Schema(description = "Period-over-period growth percentages")
    private GrowthMetricsDTO growthMetrics;

    // ─── Nested DTOs ─────────────────────────────────────────────────────────

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Aggregate sales totals for the period (excludes CANCELLED orders)")
    public static class SummaryDTO {

        @Schema(description = "Total number of non-cancelled sales orders in the period", example = "125")
        private int totalOrders;

        @Schema(description = "Total revenue from non-cancelled sales orders", example = "650000.00")
        private BigDecimal totalRevenue;

        @Schema(description = "Average order value (totalRevenue ÷ totalOrders)", example = "5200.00")
        private BigDecimal averageOrderValue;

        @Schema(description = "Total quantity of items sold across all line items", example = "850")
        private int totalItemsSold;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Top-selling product entry")
    public static class TopProductDTO {

        @Schema(description = "Product ID", example = "10")
        private Long productId;

        @Schema(description = "Product SKU", example = "LAP-001")
        private String sku;

        @Schema(description = "Product name", example = "Dell Laptop XPS 15")
        private String name;

        @Schema(description = "Total units sold in the period", example = "85")
        private int unitsSold;

        @Schema(description = "Total revenue generated by this product in the period", example = "110499.15")
        private BigDecimal revenue;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Top customer by total spend entry")
    public static class TopCustomerDTO {

        @Schema(description = "Customer ID", example = "15")
        private Long customerId;

        @Schema(description = "Customer contact name", example = "Sarah Johnson")
        private String customerName;

        @Schema(description = "Number of sales orders placed by this customer in the period", example = "12")
        private int orderCount;

        @Schema(description = "Total amount spent by this customer in the period", example = "85000.00")
        private BigDecimal totalSpent;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Single-day sales data point")
    public static class DailyTrendDTO {

        @Schema(description = "Calendar date", example = "2026-02-01")
        private LocalDate date;

        @Schema(description = "Number of non-cancelled sales orders on this date", example = "15")
        private int orders;

        @Schema(description = "Revenue from non-cancelled sales orders on this date", example = "78000.00")
        private BigDecimal revenue;

        @Schema(description = "Total items sold across all line items on this date", example = "95")
        private int itemsSold;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Period-over-period growth percentages. Positive values indicate growth, negative indicate decline.")
    public static class GrowthMetricsDTO {

        @Schema(description = "Revenue growth vs the previous equal-length period (%)", example = "12.07")
        private double revenueGrowth;

        @Schema(description = "Order count growth vs the previous equal-length period (%)", example = "8.50")
        private double orderGrowth;

        @Schema(description = "Average order value growth vs the previous equal-length period (%)", example = "3.20")
        private double averageOrderValueGrowth;
    }
}