package com.moeware.ims.dto.dashboard;

import java.math.BigDecimal;
import java.util.List;

import com.moeware.ims.enums.dashboard.DashboardPeriod;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Chart data for the top-selling-products widget.
 * Each entry shows units sold, revenue, and percentage share of total revenue.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "Top-selling products ranked by revenue for the top-selling-products chart widget")
public class DashboardTopSellingProductsResponse {

    @Schema(description = "The resolved time window used to rank products", example = "MONTH")
    private DashboardPeriod period;

    @Schema(description = "Products ranked by revenue descending, limited to the requested count")
    private List<TopProductDTO> products;

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "A single product entry in the top-selling chart")
    public static class TopProductDTO {

        @Schema(description = "Product ID", example = "10")
        private Long productId;

        @Schema(description = "Product SKU", example = "LAP-001")
        private String sku;

        @Schema(description = "Product name", example = "Dell Laptop XPS 15")
        private String name;

        @Schema(description = "Total units sold across all non-cancelled sales orders in the period", example = "85")
        private int unitsSold;

        @Schema(description = "Total revenue generated by this product in the period", example = "110499.15")
        private BigDecimal revenue;

        @Schema(description = "This product's revenue as a percentage of total revenue across all returned products (0–100)", example = "17.0")
        private double percentage;
    }
}