# ─────────────────────────────────────────────────────────────
#  Dev Inventory  (inventory/dev/hosts.ini)
#  Run against a local VM or Docker container for testing
#  Usage: ansible-playbook -i inventory/dev site.yml
# ─────────────────────────────────────────────────────────────


[webservers]
dev-local ansible_host=127.0.0.1 ansible_connection=local


[app:children]
webservers

[all:vars]
ansible_python_interpreter=/usr/bin/python3
env=dev